travis:
  secure:
    BINSTAR_TOKEN: mbhpycGL+a0x+1IBLugY4xRS0tOS1zjxg021OpbC14KVqNfKr7doY+tOeAHQ8OOaPx6t1ZfV0gYz/jFIl/iE0Uz+zpz6jzDWIdyKTqfnbqnuQ9d4m0DoFH0/r+PcvQxhzTzv3WVxWCJn0favY8dflRkHKeetDOz5k9puNaoIpRIgK8YtPJVCsWHBiwYOJrrOK9nHJNndUWAnQF5vs56e+bGLli65LVMCAGTWWHlaG9+AoBn1lVSvSN88/4eOSMnRSGXwqsmXrmjacf5Z9yBYm5Y5gzpGqbKzTOHFsmTpca5Yos3p2sE5Gs4nT4w5TGdZdzTGJR43K4R7NZNI8Hyh+/scuGmfPYMGG+C0goTO27LUy/zOirJk9wPaFhcmAopj2HsVOYw1324w3ucrSkXZorDV3oQ6cZK0IY1DPcKsT9C5GrZ43n/MBckk+qySSDZUzqEtLr37HkDc/Uk3+EOHRlzxEmRMb+Tb+55rM5CrWYWMPcyI3rLJu9mWudWTKYM96kkQDWh6b40d1NekBt3Cs49irb83wP8G/THpN2tUs2N3GyKE53YxjFXMkOrQ8zDsUxrPqTzBKLhUELqpzAqqz720j/AFAitCiRkoyLvwT0A4NEOIaqQIwnyhKMfonD7fThelodmyjeiGW82YtgqcN8Kdtr+TzaBkDQW7A7tlNXY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
